/** Closed ActionKind enum — ~40 members. The LLM cannot invent a new kind. */

export const ACTION_KINDS = [
  "observe_snapshot",
  "record_finding",
  "inspect_indexation",
  "rewrite_title",
  "rewrite_meta_description",
  "rewrite_og_title",
  "rewrite_og_description",
  "rewrite_alt_text",
  "fix_heading",
  "add_h1",
  "repair_broken_internal_link",
  "regenerate_sitemap",
  "submit_sitemap",
  "add_lang",
  "add_viewport",
  "fix_title_length",
  "fix_meta_length",
  "add_image_dimensions",
  "insert_internal_link",
  "add_jsonld",
  "update_jsonld",
  "remove_invalid_jsonld",
  "refresh_content",
  "create_page",
  "add_breadcrumb",
  "add_faq_schema",
  "add_article_schema",
  "add_product_schema",
  "add_og_image",
  "edit_robots_txt",
  "edit_meta_robots",
  "add_redirect",
  "change_canonical",
  "change_hreflang",
  "delete_page",
  "send_outreach_email",
  "submit_disavow",
  "edit_llms_txt",
  "buy_link",
  "build_pbn",
  "exchange_links",
  "cloak",
  "sneaky_redirect",
  "hide_text",
  "write_third_party",
  "gate_reviews",
  "incentivize_reviews",
  "scrape_serp",
  "generate_ymyl",
  "generate_affiliate",
] as const;

export type ActionKind = (typeof ACTION_KINDS)[number];

export const ACTION_KIND_SET: ReadonlySet<string> = new Set(ACTION_KINDS);

/** Policy matrix from PLAN §4. T3/T4 are not overridable. */
export const KIND_TIER: Record<ActionKind, 0 | 1 | 2 | 3 | 4> = {
  observe_snapshot: 0,
  record_finding: 0,
  inspect_indexation: 0,
  rewrite_title: 1,
  rewrite_meta_description: 1,
  rewrite_og_title: 1,
  rewrite_og_description: 1,
  rewrite_alt_text: 1,
  fix_heading: 1,
  add_h1: 1,
  repair_broken_internal_link: 1,
  regenerate_sitemap: 1,
  submit_sitemap: 1,
  add_lang: 1,
  add_viewport: 1,
  fix_title_length: 1,
  fix_meta_length: 1,
  add_image_dimensions: 1,
  insert_internal_link: 2,
  add_jsonld: 2,
  update_jsonld: 2,
  remove_invalid_jsonld: 2,
  refresh_content: 2,
  create_page: 2,
  add_breadcrumb: 2,
  add_faq_schema: 2,
  add_article_schema: 2,
  add_product_schema: 2,
  add_og_image: 2,
  edit_robots_txt: 3,
  edit_meta_robots: 3,
  add_redirect: 3,
  change_canonical: 3,
  change_hreflang: 3,
  delete_page: 3,
  send_outreach_email: 3,
  submit_disavow: 3,
  edit_llms_txt: 3,
  buy_link: 4,
  build_pbn: 4,
  exchange_links: 4,
  cloak: 4,
  sneaky_redirect: 4,
  hide_text: 4,
  write_third_party: 4,
  gate_reviews: 4,
  incentivize_reviews: 4,
  scrape_serp: 4,
  generate_ymyl: 4,
  generate_affiliate: 4,
};

export const TWO_KEY_KINDS: ReadonlySet<ActionKind> = new Set([
  "edit_robots_txt",
  "edit_meta_robots",
  "add_redirect",
  "change_canonical",
  "change_hreflang",
  "delete_page",
  "submit_disavow",
  "edit_llms_txt",
]);

export const NEW_PAGE_KINDS: ReadonlySet<ActionKind> = new Set(["create_page"]);

export const CONTENT_REFRESH_KINDS: ReadonlySet<ActionKind> = new Set(["refresh_content"]);

export const CONTENT_GEN_KINDS: ReadonlySet<ActionKind> = new Set([
  "refresh_content",
  "create_page",
  "generate_ymyl",
  "generate_affiliate",
]);

export function isActionKind(value: string): value is ActionKind {
  return ACTION_KIND_SET.has(value);
}
