import { chromium } from 'playwright';
import fs from 'fs';
const html=fs.readFileSync('./fixture3.html','utf8');
const uniq=[...new Set([...html.matchAll(/ZZ([A-Z]+?)ZZ/g)].map(m=>m[1]))];
const b=await chromium.launch(); const p=await b.newPage();
await p.setContent(html,{waitUntil:'load'});
const it=await p.evaluate(()=>document.body.innerText);
const tc=await p.evaluate(()=>document.body.textContent);
const ax=JSON.stringify(await p.evaluate(()=>Array.from(document.querySelectorAll('*')).map(e=>[e.getAttribute('aria-label'),e.getAttribute('alt'),e.getAttribute('title')]).flat().filter(Boolean)));
const ihtml=await p.content();
await b.close();
const R={'pw.innerText':it,'pw.textContent':tc,'pw.a11ySnapshot':ax,'pw.content()':ihtml};
const n=Object.keys(R);
let out='| marker | '+n.join(' | ')+' |\n|'+'---|'.repeat(n.length+1)+'\n';
for(const m of uniq) out+='| '+m+' | '+n.map(k=>R[k].includes(m)?'YES':'no').join(' | ')+' |\n';
console.log(out);
console.log('innerText tagblock present:', /[\u{E0000}-\u{E007F}]/u.test(it));
console.log('innerText ZWSP present:', it.includes('​'));
console.log('innerText RLO present:', it.includes('‮'));
