export { getDatabaseProvider, type DatabaseProvider } from "./provider.js";
export {
  CORE_TABLES,
  GOOGLE_TABLES,
  ACTION_TABLES,
  DASHBOARD_TABLES,
  CONTENT_TABLES,
  ALL_TABLES,
  type CoreTable,
  type GoogleTable,
  type ActionTable,
  type DashboardTable,
  type ContentTable,
  type AppTable,
} from "./tables.js";
export {
  sites,
  crawls,
  pages,
  pageSnapshots,
  findings,
  actions,
  changes,
  changeSnapshots,
  credentials,
  costLedger,
  jobs,
  settings,
  auditLog,
  gscConnections,
  ga4Connections,
  gscDaily,
  gscPageDaily,
  gscQueryDaily,
  gscUrlInspections,
  ga4Daily,
  ga4LandingDaily,
  cruxRecords,
  psiAudits,
  googleIncidents,
  googleChangepoints,
  gscGa4Reconciliation,
  siteVerifications,
  quotaUsage,
  adapterConnections,
  urlAllowlist,
  entitySightings,
  twoKeyApprovals,
  reports,
  styleProfiles,
  contentBriefs,
  contentDrafts,
  publishGateResults,
  sqliteSchema,
  pgSchema,
} from "./schema.js";
export {
  openSqlite,
  applySqliteSchema,
  assertDbNotWorldReadable,
  type SqliteDatabase,
} from "./client.js";
export {
  searchFindingsFts,
  type FindingSearchHit,
  type FindingSearchQuery,
} from "./fts.js";
